export const AIRPORTS = [
  "Jakarta (CGK) – Soekarno-Hatta",
  "Jakarta (HLP) – Halim Perdanakusuma",
  "Bali (DPS) – Ngurah Rai",
  "Yogyakarta (YIA) – Yogyakarta International Airport",
  "Surabaya (SUB) – Juanda",
  "Medan (KNO) – Kualanamu",
  "Makassar (UPG) – Sultan Hasanuddin",
  "Balikpapan (BPN) – Sultan Aji Muhammad Sulaiman",
  "Semarang (SRG) – Ahmad Yani",
  "Palembang (PLM) – Sultan Mahmud Badaruddin II",
  "Pekanbaru (PKU) – Sultan Syarif Kasim II",
  "Banjarmasin (BDJ) – Syamsudin Noor",
  "Pontianak (PNK) – Supadio",
  "Manado (MDC) – Sam Ratulangi",
  "Batam (BTH) – Hang Nadim",
  "Lombok (LOP) – Zainuddin Abdul Madjid",
  "Aceh (BTJ) – Sultan Iskandar Muda",
  "Padang (PDG) – Minangkabau",
  "Bengkulu (BKS) – Fatmawati Soekarno",
  "Bandung (BDO) – Husein Sastranegara",
  "Jambi (DJB) – Sultan Thaha",
  "Lampung (TKG) – Radin Inten II",
  "Tarakan (TRK) – Juwata",
  "Palangkaraya (PKY) – Tjilik Riwut",
  "Samarinda (AAP) – APT Pranoto",
  "Kupang (KOE) – El Tari",
  "Jayapura (DJJ) – Sentani",
  "Ambon (AMQ) – Pattimura",
  "Ternate (TTE) – Sultan Babullah",
  "Sorong (SOQ) – Domine Eduard Osok",
  "Biak (BIK) – Frans Kaisiepo",
  "Manokwari (MKW) – Rendani",
  "Denpasar (DPS) – Ngurah Rai",
  "Mataram (AMI) – Selaparang (non-aktif, opsional)",
  "Palu (PLW) – Mutiara SIS Al-Jufrie",
  "Kendari (KDI) – Haluoleo",
  "Gorontalo (GTO) – Jalaluddin",
  "Banyuwangi (BWX) – Blimbingsari",
  "Malang (MLG) – Abdul Rachman Saleh",
  "Solo (SOC) – Adi Soemarmo",
  "Pontianak (PNK) – Supadio",
  "Nias (GNS) – Binaka",
  "Labuan Bajo (LBJ) – Komodo",
  "Ende (ENE) – H. Hasan Aroeboesman"
]
